wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1710002940.285114
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 1
      - 5
      13: darwin-arm64
